# Generated by Django 5.2.6 on 2025-11-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_media_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='source_url',
        ),
    ]
