# Generated by Django 5.2.6 on 2025-11-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_media_source_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringpost',
            name='workType',
        ),
        migrations.RemoveField(
            model_name='post',
            name='skills',
        ),
        migrations.AddField(
            model_name='hiringpost',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='hiring_posts', to='posts.skill'),
        ),
    ]
