# Generated by Django 5.2.6 on 2025-11-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_hiringpost_worktype_remove_post_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('rental', 'Rental Post'), ('hiring', 'Hiring Post')], editable=False, max_length=50, null=True),
        ),
    ]
