# Generated by Django 5.2.6 on 2025-11-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='kind',
        ),
        migrations.AddField(
            model_name='category',
            name='is_hiring_category',
            field=models.BooleanField(default=True, help_text="ติ๊กถ้าหมวดหมู่นี้ใช้สำหรับ 'จ้างงาน'"),
        ),
        migrations.AddField(
            model_name='category',
            name='is_rental_category',
            field=models.BooleanField(default=True, help_text="ติ๊กถ้าหมวดหมู่นี้ใช้สำหรับ 'ให้เช่า'"),
        ),
    ]
