# Generated by Django 5.2.6 on 2025-11-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_category_is_hiring_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_hiring_category',
            field=models.BooleanField(default=True, verbose_name='hiring'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_rental_category',
            field=models.BooleanField(default=True, verbose_name='rental'),
        ),
    ]
