# Generated by Django 5.2.6 on 2025-12-10 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookings',
            field=models.ManyToManyField(blank=True, related_name='booked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
